"""Added description

Revision ID: 21461174e48a
Revises: dcbf1ebb830d
Create Date: 2018-01-12 14:27:30.077347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21461174e48a'
down_revision = 'dcbf1ebb830d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('description', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'description')
    # ### end Alembic commands ###
