"""Added description to items.

Revision ID: 901e2c6ad545
Revises: dcbf1ebb830d
Create Date: 2017-12-06 08:29:24.256692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '901e2c6ad545'
down_revision = 'dcbf1ebb830d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('description', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'description')
    # ### end Alembic commands ###
