"""adding checkbox to posts

Revision ID: 9ccf6c29b083
Revises: d6e11df86952
Create Date: 2018-02-07 11:42:59.449140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ccf6c29b083'
down_revision = 'd6e11df86952'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('done', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'done')
    # ### end Alembic commands ###
